close all;
clear all;
f = figure;
w0 = 0.05;
w1 = 0.999;
[a, b] = make_logistic(w0, w1);
N=500;
xrange = linspace(-1,1,N);
yrange = linspace(-1,1,N);
[x,y] = meshgrid(xrange,yrange);
theta = y./sqrt(x.^2+y.^2);
theta_logistic = 1./(1+exp(a*theta+b));
data = theta_logistic.*(x.^2+y.^2<=1)+(x.^2+y.^2>1);
contourf(x,y,data,100,'LineColor','none');
hold on;
daspect([1 1 1]);
a = annotation('ellipse','LineWidth',3);
a.Parent = f.CurrentAxes;
a.Position = [-1 -1 2 2];
colormap("hot");
colorbar;
caxis([0 1]);